name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Adicionamos este bloco para forçar a leitura do segredo para uma variável de ambiente
    env:
      API_KEY_SECRET: ${{ secrets.SECRET_API_SHEETS }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Verify Secret Presence 🕵️
        run: |
          if [ -z "${{ env.API_KEY_SECRET }}" ]; then
            echo "::error::ERRO FATAL: O segredo SECRET_API_SHEETS está vazio ou não foi encontrado nas configurações do repositório."
            exit 1
          else
            echo "Segredo encontrado com sucesso."
          fi

      - name: Create config.js file 🤫
        # Agora usamos a variável de ambiente que criamos e verificamos acima
        run: |
          echo "const API_KEY = '${{ env.API_KEY_SECRET }}';" > config.js
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .